### ISSUE TITLE
Ghidra

### ISSUE THREAD

**Issue by mumbel** [riscv/riscv-software-list#8]
I've have submitted a PR for a RISC-V processor module in Ghidra, a software reverse engineering (SRE) framework.  https://github.com/NationalSecurityAgency/ghidra

Could I leave this here as a place holder until it's merged and then be added to this list after that process is completed?  I would also encourage anyone to try out the tool and welcome any suggestions/comments/feedback/PRs related to the RISC-V implementation (my issue tracker or in the PR itself).  The DevGuide.md is fairly straight forward to build from source.

**Comment by mgielda** [comment]
Thanks! Will keep this in mind. For reference - https://github.com/NationalSecurityAgency/ghidra/pull/932

**Comment by mumbel** [comment]
https://github.com/mumbel/ghidra_riscv

A bit more manageable for anyone who wanted to test, you don't have build the whole Ghidra project, just this directory with the path to the ghidra install dir

**Comment by mgielda** [comment]
Hi @mumbel, I can see this was actually merged a while ago! Do you think you'd like this to go on the list, in the security section? I for one support the idea!

**Comment by mumbel** [comment]
Yeah, I think that's fine and close this out.  I was holding off here thinking 9.2/9.1.3 was going to out soon (based on their previous release cycle) after it merged into master but then holidays and covid hit, it's been delayed.  Users will still need to build from master until that happens.
